### ISSUE TITLE
Fix bug - Selection / Reproduction

### ISSUE THREAD

**Issue by m-mathilde34** [m-mathilde34/Traveling-Salesman---Genetic-Algorithm#12]
@trav-d13 I've implemented the first (and easiest haha I know!! I promise I will get to the challenging one soon!!) way of getting the Ordered Crossover Reproduction method. However when I created a test for it, it keeps failing bringing up the following error: 'Cannot read field "route" because "this.parent1" is null'.

After investigation I strongly believe it is because of my coding in the Selection class, in the method getFittestIndividual() which I just c/ced the code for below: 
```
public Route getFittestIndividual(){
        Route route;
        **Route fittestIndividual = null;**
        int counter = 0;
        double max_fitness = 0;

        while(counter < k){
            route = pool.get(counter);
            if(route.fitness > max_fitness){
                max_fitness = route.fitness;
                fittestIndividual = route;
            }
            counter += 1;
        }

        return fittestIndividual;
    }
```

I think all this is because of the line 'Route fittestIndividual = null;'. I have to initialize it otherwise Java is having a meltdown over it. Do you have any suggestion to fix this?

**Comment by trav-d13** [comment]
Hey @m-mathilde34, I just had a look at your code. 
I think that the main issue is due to your `k` field inside of `Selection.java`. 
As in your test, you haven't included it as a parameter inside of your Selection constructor, as such it takes on a default size of 40. 
While your selection pool is constructed correctly, I think (like you said) the issue lies in your `findFittestIndividual()` as your counter will increase to `k` (40), but your pool is much smaller than that, so when this line gets executed `route = pool.get(counter);` I believe it returns a `Null` route which may causing the error. 

Let me know your thoughts? 
All the best!
